const QUOTES = [
  { text: 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', author: 'Robert Collier' },
  { text: 'No dejes para mañana lo que puedes hacer hoy.', author: 'Benjamin Franklin' },
  { text: 'La disciplina es el puente entre metas y logros.', author: 'Jim Rohn' },
  { text: 'El único modo de hacer un gran trabajo es amar lo que haces.', author: 'Steve Jobs' },
  { text: 'Cada experto fue alguna vez un principiante.', author: 'Helen Hayes' },
  { text: 'La motivación te pone en marcha, el hábito te mantiene.', author: 'Jim Ryun' },
  { text: 'El conocimiento es poder.', author: 'Francis Bacon' },
  { text: 'Nunca es tarde para ser lo que podrías haber sido.', author: 'George Eliot' },
  { text: 'El secreto de salir adelante es empezar.', author: 'Mark Twain' },
  { text: 'Estudia no para saber más, sino para saber mejor.', author: 'Séneca' },
  { text: 'La educación es el arma más poderosa para cambiar el mundo.', author: 'Nelson Mandela' },
  { text: 'No cuentes los días, haz que los días cuenten.', author: 'Muhammad Ali' },
  { text: 'El futuro pertenece a quienes creen en la belleza de sus sueños.', author: 'Eleanor Roosevelt' },
  { text: 'Cree que puedes y ya estás a medio camino.', author: 'Theodore Roosevelt' },
  { text: 'La persistencia puede transformar el fracaso en un logro extraordinario.', author: 'Matt Biondi' },
  { text: 'Lo que no te desafía, no te cambia.', author: 'Fred DeVito' },
  { text: 'Un poco de progreso cada día suma grandes resultados.', author: 'Satya Nani' },
  { text: 'Tu única limitación eres tú mismo.', author: 'Anónimo' },
  { text: 'Haz hoy lo que otros no quieren, mañana vivirás como otros no pueden.', author: 'Jerry Rice' },
  { text: 'El aprendizaje nunca agota la mente.', author: 'Leonardo da Vinci' },
  // New quotes
  { text: 'La constancia vence lo que la dicha no alcanza.', author: 'Proverbio español' },
  { text: 'No hay atajos para ningún lugar al que valga la pena ir.', author: 'Beverly Sills' },
  { text: 'El talento gana partidos, pero el trabajo en equipo y la inteligencia ganan campeonatos.', author: 'Michael Jordan' },
  { text: 'Empieza donde estás, usa lo que tienes, haz lo que puedas.', author: 'Arthur Ashe' },
  { text: 'La mejor forma de predecir el futuro es crearlo.', author: 'Peter Drucker' },
  { text: 'Todo parece imposible hasta que se hace.', author: 'Nelson Mandela' },
  { text: 'El esfuerzo continuo, no la fuerza o la inteligencia, es la clave para desbloquear nuestro potencial.', author: 'Winston Churchill' },
  { text: 'No busques el momento perfecto, toma el momento y hazlo perfecto.', author: 'Anónimo' },
  { text: 'Somos lo que hacemos repetidamente. La excelencia no es un acto, sino un hábito.', author: 'Aristóteles' },
  { text: 'Si puedes soñarlo, puedes lograrlo.', author: 'Walt Disney' },
  { text: 'La vida es 10% lo que te pasa y 90% cómo reaccionas.', author: 'Charles R. Swindoll' },
  { text: 'Los grandes logros requieren tiempo.', author: 'David J. Schwartz' },
  { text: 'La única persona que puedes ser es tú mismo.', author: 'Audrey Hepburn' },
  { text: 'Lo importante no es lo que sabes, sino lo que haces con lo que sabes.', author: 'Anónimo' },
  { text: 'Los límites solo existen si los aceptas.', author: 'Anónimo' },
  { text: 'No te preocupes por el fracaso. Preocúpate por las oportunidades que pierdes cuando ni siquiera lo intentas.', author: 'Jack Canfield' },
  { text: 'El mayor riesgo es no tomar ningún riesgo.', author: 'Mark Zuckerberg' },
  { text: 'Donde hay una voluntad, hay un camino.', author: 'Proverbio inglés' },
  { text: 'No midas tu progreso comparándote con otros, compárate con quien eras ayer.', author: 'Anónimo' },
  { text: 'La diferencia entre ordinario y extraordinario es ese pequeño extra.', author: 'Jimmy Johnson' },
  { text: 'Los sueños no funcionan a menos que tú trabajes.', author: 'John C. Maxwell' },
  { text: 'La paciencia es la madre de todas las ciencias.', author: 'Proverbio español' },
  { text: 'No importa lo lento que vayas, siempre que no te detengas.', author: 'Confucio' },
  { text: 'La creatividad es la inteligencia divirtiéndose.', author: 'Albert Einstein' },
  { text: 'Si quieres algo que nunca tuviste, haz algo que nunca hiciste.', author: 'Anónimo' },
  { text: 'El mejor momento para plantar un árbol fue hace 20 años. El segundo mejor momento es ahora.', author: 'Proverbio chino' },
  { text: 'No existe el fracaso, solo resultados de los que aprender.', author: 'Tony Robbins' },
  { text: 'La acción es la clave fundamental de todo éxito.', author: 'Pablo Picasso' },
  { text: 'Lo que haces hoy puede mejorar todos tus mañanas.', author: 'Ralph Marston' },
  { text: 'No hay camino hacia la felicidad: la felicidad es el camino.', author: 'Thich Nhat Hanh' },
  { text: 'El optimismo es la fe que conduce al logro.', author: 'Helen Keller' },
  { text: 'Pequeños pasos en la dirección correcta pueden ser los pasos más grandes de tu vida.', author: 'Naeem Callaway' },
  { text: 'Hazlo con pasión o no lo hagas.', author: 'Rosa Nouchette Carey' },
  { text: 'El dolor que sientes hoy será la fuerza que sentirás mañana.', author: 'Anónimo' },
  { text: 'No cuentes las horas, haz que las horas cuenten.', author: 'Anónimo' },
  { text: 'La vida empieza al final de tu zona de confort.', author: 'Neale Donald Walsch' },
  { text: 'Cuanto más duro trabajo, más suerte tengo.', author: 'Thomas Jefferson' },
  { text: 'El cambio es la ley de la vida.', author: 'John F. Kennedy' },
  { text: 'Si no construyes tu sueño, alguien te contratará para construir el suyo.', author: 'Farrah Gray' },
  { text: 'Lo que consigues al alcanzar tus metas no es tan importante como en lo que te conviertes.', author: 'Zig Ziglar' },
];

export function getDailyQuote() {
  const today = new Date();
  const dayOfYear = Math.floor((today.getTime() - new Date(today.getFullYear(), 0, 0).getTime()) / 86400000);
  return QUOTES[dayOfYear % QUOTES.length];
}
